AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'nayakapidemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'nayakapi-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'prashantnayak'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'